language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: aHX1zEf2+PLHPhISw1psS1DP35JOH6asdrfXE2MKCe5R0sBT857QeS/fRd+Qf3msVf2LcI/irNbZ32indaeX8JzOFnsdbyNQTCVGn1S+nsRwEO7l8Fjkhh69LE/AGBtLER6wvhI8ulZ1JniwsQvjkE3m/wXr8Ra/6nFOEViA7gIJIV/Yvc2r8nb50EjbHkPrgLBHB7tEMYL0xMakHxR4rIHHo1YUnBHbMtv9Qa6ZAKD5nZZWK+2daobr8OKQT30SlB+SsngqUM0d1TYSVtDoa8aCPlq6+cIbccfLdznkcdurIzGWVjqpc7UTyZ8gib8eeGUzf0/LrlGxzsDFCAGG8FFUs7ngD8CKnitm3rFAQj3ebtS244f3p4ErXMSq1PZ36j7sz/jOCmBZ/rN0NpeaV/lu2bq5aZm2kzs1WCtZx6QzFPq6rxBnln/gXIS1gKTHfq/IvUf/xX5Krc1iGJTUswBmMUvNlAUIFaUy8mISLbGjfepb/jd+tHxhXx5vYX1jXAnWjhUpwaN/RE8Xtjf/a9RYOklJc/h2v6tyVBwVP+IDxO5dvnhaV8/ZJEHUb3YRjWRLuiDNAx9PsqafvkF8R3+e19z+Bu16gF/J50Rukx+hB5F7OnyF8a4ZzFat8/kOblqmvxdK2et4OOPASUlJv/GjrglcYfm4wzUVrf2nDMU=
  app: flasktaskr-project
  on:
    branch: master
    python: '3.4'
    repo: Danielss12/flasktaskr_project
